export const varToScreen = {
  // Engine Details
  engineId: { type: "select", displayText: "Engine ID", radioOptions: null },
  engineMake: {
    type: "select",
    displayText: "Engine Make",
    radioOptions: null,
  },
  engineModel: {
    type: "select",
    displayText: "Engine Model",
    radioOptions: null,
  },
  engineModelYear: {
    type: "select",
    displayText: "Engine Model Year",
    radioOptions: null,
  },
  engineType: {
    type: "select",
    displayText: "Engine Type",
    radioOptions: null,
  },
  typeDesignation: {
    type: "select",
    displayText: "Type Designation",
    radioOptions: null,
  },
  askingPrice: {
    type: "select",
    displayText: "Asking Price",
    radioOptions: null,
  },

  // Condition
  condition: { type: "select", displayText: "Condition", radioOptions: null },
  usedCondition: {
    type: "select",
    displayText: "Used Condition",
    radioOptions: null,
  },
  seller: { type: "select", displayText: "Seller", radioOptions: null },
  offeredBy: { type: "select", displayText: "Offered By", radioOptions: null },
  lastSurveyDate: {
    type: "select",
    displayText: "Last Survey Date",
    radioOptions: null,
  },
  brokerValuation: {
    type: "select",
    displayText: "Broker Valuation",
    radioOptions: null,
  },

  // General
  engineClassification: {
    type: "select",
    displayText: "Engine Classifiable",
    radioOptions: null,
  },
  certification: {
    type: "select",
    displayText: "Certification",
    radioOptions: null,
  },
  manufacturerWarranty: {
    type: "select",
    displayText: "Manufacturer Warranty",
    radioOptions: null,
  },
  engineSerialNumber: {
    type: "select",
    displayText: "Engine Serial Number",
    radioOptions: null,
  },
  ceDesignCategory: {
    type: "select",
    displayText: "CE Design Category",
    radioOptions: null,
  },
  numberDrives: {
    type: "select",
    displayText: "Number of Drives",
    radioOptions: null,
  },
  numberEngines: {
    type: "select",
    displayText: "Number of Engines",
    radioOptions: null,
  },
  range: { type: "select", displayText: "Engine Range", radioOptions: null },
  cruisingSpeed: {
    type: "select",
    displayText: "Cruising Speed",
    radioOptions: null,
  },
  driveType: { type: "select", displayText: "Drive Type", radioOptions: null },
  engineHours: {
    type: "select",
    displayText: "Engine Hours",
    radioOptions: null,
  },
  ignitionSystem: {
    type: "select",
    displayText: "Ignition System",
    radioOptions: null,
  },
  noiseLevel: {
    type: "select",
    displayText: "Noise Level",
    radioOptions: null,
  },
  engineSoundproofingKits: {
    type: "select",
    displayText: "Engine Soundproofing Kits",
    radioOptions: null,
  },

  // Guest Requirements
  skipperIncluded: {
    type: "select",
    displayText: "Captain Included",
    radioOptions: null,
  },
  crewIncluded: {
    type: "select",
    displayText: "Crew Included",
    radioOptions: null,
  },
  crewUniformPreferences: {
    type: "select",
    displayText: "Crew Uniform Preferences",
    radioOptions: null,
  },
  localCuisinePreferences: {
    type: "select",
    displayText: "Cuisine Preferences",
    radioOptions: null,
  },
  cateringRequired: {
    type: "select",
    displayText: "Catering Required",
    radioOptions: null,
  },
  carParkingAvailable: {
    type: "select",
    displayText: "Car Parking Available",
    radioOptions: null,
  },
  specialRequirementsRequests: {
    type: "select",
    displayText: "Special Requirements",
    radioOptions: null,
  },

  // Transmission
  transmissionType: {
    type: "select",
    displayText: "Transmission Type",
    radioOptions: null,
  },
  gearShift: { type: "select", displayText: "Gear Shift", radioOptions: null },
  gearRatio: { type: "select", displayText: "Gear Ratio", radioOptions: null },
  gearShiftType: {
    type: "select",
    displayText: "Gear Shift Type",
    radioOptions: null,
  },
  flywheelSAE14: {
    type: "select",
    displayText: "Flywheel SAE",
    radioOptions: null,
  },
  siluminFlywheelHousing: {
    type: "select",
    displayText: "Flywheel Housing",
    radioOptions: null,
  },
  camshaft: { type: "select", displayText: "Camshaft", radioOptions: null },
  crankshaftAlloy: {
    type: "select",
    displayText: "Crankshaft Alloy",
    radioOptions: null,
  },
  crankcaseDesign: {
    type: "select",
    displayText: "Crankcase Design",
    radioOptions: null,
  },

  // Installation & Mounting
  engineMountingOrientation: {
    type: "select",
    displayText: "Engine Mounting Orientation",
    radioOptions: null,
  },
  engineSuspension: {
    type: "select",
    displayText: "Engine Suspension",
    radioOptions: null,
  },
  engineMountingType: {
    type: "select",
    displayText: "Engine Mounting Type",
    radioOptions: null,
  },
  mountingBracketMaterial: {
    type: "select",
    displayText: "Mounting Bracket Material",
    radioOptions: null,
  },
  alignmentRequirements: {
    type: "select",
    displayText: "Alignment Requirements",
    radioOptions: null,
  },
  engineBlock: {
    type: "select",
    displayText: "Engine Block",
    radioOptions: null,
  },

  // Service & Maintenance
  scheduledMaintenancePlan: {
    type: "select",
    displayText: "Scheduled Maintenance Plan",
    radioOptions: null,
  },
  serviceInterval: {
    type: "select",
    displayText: "Service Interval",
    radioOptions: null,
  },
  maintenanceLogRequirements: {
    type: "select",
    displayText: "Maintenance Log Requirements",
    radioOptions: null,
  },
  availabilityofSpareParts: {
    type: "select",
    displayText: "Availability of Spare Parts",
    radioOptions: null,
  },
  operationMode: {
    type: "select",
    displayText: "Operation Mode",
    radioOptions: null,
  },
  lastServiceDate: {
    type: "select",
    displayText: "Last Service Date",
    radioOptions: null,
  },
};

export const varToDb = {
  // Engine Details
  marisailVesselID: "Marisail_Vessel_ID",
  dataSouce: "DATA_SOURCE",
  engineId: "Engine_ID",
  engineMake: "Engine_Make",
  engineModel: "Engine_Model",
  engineModelYear: "Engine_Model_Year",
  engineType: "Engine_Type",
  typeDesignation: "Type_Designation",
  askingPrice: "Asking_Price",

  // Condition
  condition: "Condition",
  usedCondition: "Used_Condition",
  seller: "Seller",
  offeredBy: "Offered_By",
  lastSurveyDate: "Last_Survey_Date",
  brokerValuation: "Broker_Valuation",

  // General
  engineClassification: "Engine_Classifiable",
  certification: "Certification",
  manufacturerWarranty: "Manufacturer_Warranty",
  engineSerialNumber: "Engine_Serial_Number",
  ceDesignCategory: "CE_Category",
  numberDrives: "Number_Drives",
  numberEngines: "Number_Engines",
  range: "Engine_Range",
  cruisingSpeed: "Cruise_Speed",
  driveType: "Drive_Type",
  engineHours: "Engine_Hours",
  ignitionSystem: "Ignition_System ",
  noiseLevel: "Noise_Level",
  engineSoundproofingKits: "Engine_Soundproofing_Kits",

  // Guest Requirements
  skipperIncluded: "Captain_Included",
  crewIncluded: "Crew_Included",
  crewUniformPreferences: "Crew_Uniform",
  localCuisinePreferences: "Cuisine_Preferences",
  cateringRequired: "Catering_Required",
  carParkingAvailable: "Car_Parking",
  specialRequirementsRequests: "Special_Requirements",

  // Transmission
  transmissionType: "Transmission_Type",
  gearShift: "Gear_Shift",
  gearRatio: "Gear_Ratio",
  gearShiftType: "Gear_Shift_Type",
  flywheelSAE14: "Flywheel_SAE",
  siluminFlywheelHousing: "Flywheel_Housing",
  camshaft: "Camshaft",
  crankshaftAlloy: "Crankshaft_Alloy",
  crankcaseDesign: "Crankcase_Design",

  // Installation & Mounting
  engineMountingOrientation: "Engine_Mounting_Orientation",
  engineSuspension: "Engine_Suspension",
  engineMountingType: "Engine_Mounting_Type",
  mountingBracketMaterial: "Mounting_Bracket_Material",
  alignmentRequirements: "Alignment_Requirements",
  engineBlock: "Engine_Block",

  // Service & Maintenance
  scheduledMaintenancePlan: "Scheduled_Maintenance_Plan",
  serviceInterval: "Service_Interval",
  maintenanceLogRequirements: "Maintenance_Log_Requirements",
  availabilityofSpareParts: "Availability_Spare_Parts",
  operationMode: "Operation_Mode",
  lastServiceDate: "Last_Service_Date",

  // Equipment
  engineManagementSystem: "EMS",
  engineControlSystem: "Engine_Control_System ",
  unitInjectors: "Unit_Injectors",
  turbocharger: "Turbocharger",
  turbocharging: "Turbocharging",
  starterMotor: "Starter_Motor",
  protectionCovers: "Protection_Covers",
  closedCrankcaseVentilation: "Crankcase_Ventilation",
  heatExchanger: "Heat_Exchanger",
  heatExchangerWithExpansionTank: "Heat_Exchanger_WET",
  seaWaterPump: "Sea_Water_Pump",
  seaWaterCooledChargeAirCooler: "Charge_Air_Cooler",
  workingPrinciple: "Working_Principle",
  compressionRatio: "Compression_Ratio",
  pistonSpeedAt1500Rpm: "Piston_Speed_1500",
  pistonSpeedAt1800Rpm: "Piston_Speed_1800",
  firingOrder: "Firing_Order",
  pistons: "Pistons",
  connectionRods: "Connection_Rods",
  auxiliaryPowerTakeOff: "Auxiliary_Power_TakeOff",
  remoteControlSystems: "Remote_Control_Systems",

  // Dimensions
  displacement: "Displacement",
  length: "Length",
  width: "Width",
  height: "Height",
  lengthFromFrontEndToEdgeOfFlywheelHousing: "Engine_Length",
  engineWeight: "Engine_Weight",
  dryWeight: "Dry_Weight",
  weight: "Weight_Excl_Oil",
  weightWithHeatExchanger: "Weight_Heat_Exchanger",
  weightWithKeelCooling: "Weight_Heat_Exchanger",

  // Performance
  nominalRating: "Nominal_Rating",
  enginePerformance: "Engine_Performance",
  maxPowerOutput: "Max_Power_Output",
  maxPower: "Max._Power",
  maxSpeed: "Maximum_Speed",
  supercharged: "Supercharged ",
  valveTrain: "Valve_Train",
  grossPowerFullLoadKw: "GP_Full_Load",
  grossPowerFullLoadHp: "GP_Full_Load_Metric",
  grossPowerPropellerCurveKw: "GP_Propeller_Curve",
  grossPowerPropellerCurveHp: "GP_Propeller_Curve_Metric",
  grossTorque: "Gross_Torque",
  continuousPower: "Continuous_Power",
  maximumContinuousRating: "Maximum_Continuous_Rating",
  engineSpeedRange: "Engine_Speed_Range",
  engineEfficiency: "Engine_Efficiency",
  powertoWeightRatio: "Power_Weight_Ratio",

  // Cylinders
  cylinderConfiguration: "Cylinder_Configuration",
  numberCylinders: "Number_Cylinders",
  cylindersArrangement: "Cylinders_Arrangement",
  numberValves: "Number_Valves",
  valveperCylinder: "Valve_per_Cylinder",
  boreXStroke: "Bore_Stroke",
  bore: "Bore",
  stroke: "Bore_Stroke",

  // RPM
  idleRPM: "Idle_RPM",
  ratedSpeed: "Rated_Speed",
  rpmMaxPower: "RPM_Max_Power",

  // Torque
  maximumTorque: "Idle_RPM",
  maximumTorqueAtSpeed: "Rated_Speed",
  torqueAtRatedSpeed: "RPM_Max_Power",

  // Cooling System
  aftercooled: "Aftercooled",
  coolingSystem: "Cooling_System",
  closedCoolingSystem: "Closed_Cooling_System",
  openCoolingSystem: "Open_Cooling_System",
  intercooled: "Intercooled",
  recommendedCoolant: "Recommended_Coolant",
  typeOfCooling: "Cooling_Type",
  heatExchangerMaterial: "Heat_Exchanger_Material",
  heatDissipationRate: "Heat_Dissipation_Rate",
  engineLubrication: "Engine_Lubrication",
  lubricationSystem: "Lubrication_System",
  coolingCapacity: "Cooling_Capacity",
  coolingFluidType: "Cooling_Fluid_Type",
  coolingSystemPressure: "Cooling_System_Pressure",
  airFilterType: "Air_Filter_Type",
  circulationPumpType: "Circulation_Pump_Type",
  rawWaterPumpType: "Raw_Water_Pump_Type",

  // Engine Parts
  engineBearings: "Engine_Bearings",
  engineBed: "Engine_Bed",
  engineBlock: "Engine_Block",
  engineBracket: "Engine_Bracket",
  engineBreather: "Engine_Breather",
  engineCompartment: "Engine_Compartment",
  engineCompartmentVentilation: "Engine_Compartment_Ventilation",
  engineCoolingSystem: "Engine_Cooling_System",
  engineCover: "Engine_Cover",
  engineDrivenPump: "Engine_Driven_Pump",
  engineExhaustSystem: "Engine_Exhaust_System",
  engineGasketSet: "Engine_Gasket_Set",
  engineGearshift: "Engine_Gearshift",
  engineHatch: "Engine_Hatch",
  engineHourMeter: "Engine_Hour_Meter",
  engineInstrumentPanel: "Engine_Instrument_Panel",
  engineMaintenance: "Engine_Maintenance",
  engineMounts: "Engine_Mounts",
  enginePanel: "Engine_Panel",
  engineRemoteControl: "Engine_Remote_Control",
  engineStartButton: "Engine_Start_Button",
  engineStopButton: "Engine_Stop_Button",
  engineTachometer: "Engine_Tachometer",
  engineTelegraph: "Engine_Telegraph",
  engineTemperatureGauge: "Engine_Temperature_Gauge",
  engineThrottle: "Engine_Throttle",
  engineTransmission: "Engine_Transmission",
  engineTrunk: "Engine_Trunk",
  engineVoltageMeter: "Engine_Voltage_Meter",
  engineWarningLight: "Engine_Warning_Light",
  engineControlLever: "Engine_Control_Lever",
  engineControlPartsAccessories: "Engine_Control_Parts",
  engineControlRoom: "Engine_Control_Room",

  // Engine Measurements
  engineCoolingWaterFlow: "Engine_Cooling_Water_Flow",
  engineExhaustTemperature: "Engine_Exhaust_Temperature",
  engineOperatingHours: "Engine_Operating_Hours",
  enginePower: "Engine_Power",
  engineRoomVolume: "Engine_Room_Volume",
  engineRPM: "Engine_RPM",
  engineTorque: "Engine_Torque",

  // Engine Parts
  engineRoom: "Engine_Room",
  engineRoomFan: "Engine_Room_Fan",
  engineRoomFanExtractor: "Engine_Room_Extractor",
  engineRoomInsulation: "Engine_Room_Insulation",
  engineRoomLight: "Engine_Room_Light",
  engineRoomSoundproofing: "Engine_Room_Light",
  EngineRoomVentilation: "Engine_Room_Ventilation",

  // Engine Shaft
  engineShafBearing: "Engine_Shaft_Bearing",
  engineShafCollar: "Engine_Shaft_Collar",
  engineShafCoupling: "Engine_Shaft_Coupling",
  engineShafKey: "Engine_Shaft_Key",
  engineShafLog: "Engine_Shaft_Log",
  engineShafNut: "Engine_Shaft_Nut",
  engineShafSeal: "Engine_Shaft_Seal",
  engineShafSealant: "Engine_Shaft_Sealant",
  engineShafSize: "Engine_Shaft_Size",
  engineShafSpacer: "Engine_Shaft_Spacer",
  engineShafStrut: "Engine_Shaft_Strut",
  engineShafTube: "Engine_Shaft_Tube",
  engineShafWasher: "Engine_Shaft_Washer",

  // Engine Type
  ecu: "ECU",
  engineFuelType: "Engine_Fuel_Type",
  engineStroke: "Engine_Stroke",
  engineTier: "Engine_Tier",
  inboardOutboard: "Inboard_Outboard",
  mainorAuxiliary: "Main_or_Auxiliary",
  podEngine: "Pod_Engine",
  saildriveEngine: "Saildrive_Engine",
  stearingEngineControls: "Stearing_&_Engine_Controls",
  sternDriveEngine: "Stern_Drive_Engine",
  engineType: "Engine_Type",

  // Propulsion System
  bowthruster: "Bowthruster",
  propulsionSystem: "Propulsion_System",
  propulsionSystemType: "Propulsion_System_Type",
  propellerDiameter: "Propeller_Diameter_MU",
  propellerMaterial: "Propeller_Material",
  propulsion: "Propulsion",
  propellerPitch: "Propeller_Pitch",
  propellerType: "Propeller_Type",
  propellerShaftDiameter: "Propeller_Shaft_Diameter_MU",
  gearboxType: "Gearbox_Type",
  transmissionCooling: "Transmission_Cooling",
  propellerBladeMaterial: "Propeller_Blade_Material",
  propellerShaftMaterial: "Propeller_Shaft_Material",
  steeringSystem: "Steering_System",
  steeringControlType: "Steering_Control_Type",
  trimSystem: "Trim_System",
  trimTabMaterial: "Trim_Tab_Material",
  trimTabType: "Trim_Tab_Type",

  // Fuel System
  electronicFuelInjection: "EFI",
  fuelPreFilter: "Fuel_PreFilter",
  fuelFilter: "Fuel_Filter",
  fuelFilterType: "Fuel_Filter_Type",
  fuelReserve: "Fuel_Reserve",
  fuelSystem: "Fuel_System",
  fuelTankCapacity: "Fuel_Tank_Capacity_MU",
  fuelType: "Fuel_Type",
  lowestSpecificFuelConsumption: "Lowest_Fuel_Consumption",
  recommendedFuel: "Recommended_Fuel",
  fuelConsumptionAtCruisingSpeed: "Fuel_Reserve_MU",
  fuelConsumptionRate: "Fuel_Consumption_Rate",
  fuelConsumptionAtFullLoad: "FC_Full_Load",
  fuelInjectionSystemType: "Fuel_Injection_System_Type",
  fuelDeliveryPressure: "Fuel_Delivery_Pressure",
  fuelTankMaterial: "Fuel_Tank_Material",
  fuelLineDiameter: "Fuel_Line_Diameter_MU",

  // Fuel Consumption
  fuelConsumption1: "FC_3_4_Load",
  fuelConsumption2: "FC_1_2_Load",
  fuelConsumption3: "FC_Propeller_Curve_MU",
  heatRejectionToCoolant: "Heat_Rejection_MU",

  // OIL
  recommendedOil: "Recommended_Oil",
  dieselOilTank: "Diesel_Oil_Tank",
  lubeOilTank: "Lube_Oil_Tank",
  oilTank: "Oil_Tank",
  oilPressureSensor: "Oil_Pressure_Sensor",
  oilPump: "Oil_Pump",
  oilDrainPlug: "Oil_Drain_Plug",
  oilDrainManifold: "Oil_Drain_Manifold",
  oilLine: "Oil_Line",
  oilFilterCap: "Oil_Filter_Cap",
  oilSkimmer: "Oil_Skimmer",
  oilChangeInterval: "Oil_Change_Interval",
  oilCooler: "Oil_Cooler",
  oilCoolingMethod: "Oil_Cooling_Method",
  oilDipstick: "Oil_Dipstick",
  oilFiller: "Oil_Filler",
  oilFilter: "Oil_Filter",
  oilFilterBypassValve: "Filter_Bypass_Valve",
  oilFilterType: "Oil_Filter_Type",
  spinOnOilFilters: "Spin_Oil_Filter",
  oilCapacity: "Oil_Capacity_MU",
  centrifugalOilCleaner: "Centrifugal_Oil_Cleaner",
  lubricationOilPressure: "Lubrication_Oil_Pressure",

  // Electrical System
  alternator: "Alternator",
  alternatorOutput: "Alternator_Output_MU",
  batteryType: "Battery_Type",
  batteryVoltage: "Battery_Voltage",
  generatorOutput: "Battery_Voltage_MU",
  alternatorOutput: "Alternator_Output_MU",
  starterMotorVoltage: "Starter_Motor_Voltage",
  engineControlUnitModel: "ECU_Model",
  batteryChargingSystem: "Battery_Charging_System",
  integratedGenerator: "Integrated_Generator",

  // Emmissions & Environment
  emissionCompliance: "Emission_Compliance",
  exhaustSystem: "Exhaust_System",
  exhaustSystemType: "Exhaust_System_Type",
  exhaustGasAfterTreatment: "Exhaust_Gas_After_Treatment",
  exhaustGasStatus: "Exhaust_Gas_Status",
  exhaustValveTiming: "Exhaust_Valve_Timing",
  intakeValveTiming: "Intake_Valve_Timing",
  emissionControlTechnology: "Emission_Control_Technology",
  NOxEmissions: "NOx_Emissions",
  SOxEmissions: "SOx_Emissions",
  CO2Emissions: "CO2_Emissions",
  complianceWithIMOStandards: "IMO_Standards_Compliance",

  // Payment Terms
  paymentTerms: "Payment_Terms",

  // Safety & Monitoring
  currency: "Currency",
  engineMonitoringSystems: "Engine_Monitoring_Systems",
  preferredPaymentMethods: "Preferred_Payment",
  overheatProtection: "Overheat_Protection",
  invoiceReceiptProcedures: "Invoice_Receipt",
  lowOilPressureAlarm: "Low_Oil_Pressure_Alarm",
  emergencyStopSystem: "Emergency_Stop_System",
  calculatePricePay: "Calculate",
  priceLabel: "Price_Label",
};
